
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  database: lab1_1412392_1412075_development
  host: db
  username: web
  password: 123
 
test:
  <<: *default
  database: lab1_1412392_1412075_test


production:
  <<: *default
  database: lab1_1412392_1412075_production
  username: lab1_1412392_1412075
  password: <%= ENV['LAB1_1412392_1412075_DATABASE_PASSWORD'] %>
